### ISSUE TITLE
I am getting the "too many sessions" warning on ptp

### ISSUE THREAD

**Issue by carpediem13** [winneon/ptpfreeleech#2]
Hi, I'm getting the "too many sessions" warning using this script, looks like sessions didn't expire automatically after 30 mins. Any idea what's the reason?

**Comment by winneon** [comment]
Did you manage to solve your issue?
-- 

Jesse

**Comment by carpediem13** [comment]
Looks like it's because these sessions didn't expire as they supposed to be, it's working fine now, however  I wonder if it's possible to call logout after it grab the torrents.
